Get ApplicationId Component
arup-group/SpeckleRhino pull request #1
Opened 2020-09-02 18:22 UTC by megankarbowski

2020-09-03 09:08 UTC, HughGrovesArup commented on SpeckleGrasshopper/SpeckleGrasshopper.csproj
> +      <Version>6.28.20199.17141</Version>
Might need to be a bit careful here. Not sure what version the standard Arup install is on and you don't want to peg this to a version that Arup staff cant use. I doubt you need any of the new features for either so I'd be tempted to revert all Rhino related packages.

2020-09-03 09:13 UTC, HughGrovesArup requested changes
Some tweaks needed. Wait for @daviddekoning to comment before making any changes.

2020-09-03 09:13 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +          "Gets a speckle object and returns the ApplicationId. \n For example, 'prop.subprop.subsubprop'.",
With the way its setup currently users can only access top level properties / prop dictionary entries (i.e. no accessing nested fields) so need to remove the `prop.subprop.subsubprop` part.

@daviddekoning - is this approach acceptable?

2020-09-03 09:13 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      // would i check the user's input here?
Nope, check users input in `SolveInstance()`

2020-09-03 09:13 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      pManager.AddTextParameter("Path", "P", "Path of desired property (Should be ApplicationId).\nExample:'ApplicationId'", GH_ParamAccess.item);
Hmm, is this a 'get application id' component, or a 'get any top-level property' component?

If the former, get rid of this input and just hard code (I'd be tempted to say the latter is more useful though and we can just teach users to ask for the application id?) @daviddekoning

2020-09-03 09:13 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      pManager.AddGenericParameter("Output", "O", "Output value.", GH_ParamAccess.list);
Why a list? Sure just an item.

2020-09-03 09:13 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +        return Properties.Resources.json;
Before release we will want a new icon

2020-09-03 16:03 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +          "Gets a speckle object and returns the ApplicationId. \n For example, 'prop.subprop.subsubprop'.",
we should provide the capability to access nested fields. It will save a lot of spaghetti.

2020-09-03 16:05 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      pManager.AddGenericParameter("Output", "O", "Output value.", GH_ParamAccess.list);
yes, this is a One to One component: https://www.youtube.com/watch?v=ob3ER12ut3Y&t=1s

@megankarbowski , that video was released a couple of weeks ago and is very helpful for understanding GH data

2020-09-03 16:05 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      pManager.AddTextParameter("Path", "P", "Path of desired property (Should be ApplicationId).\nExample:'ApplicationId'", GH_ParamAccess.item);
this component is just for the `applicationID`, there is a second one (`Query Speckle Object`) that will be more general.

2020-09-03 16:07 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      pManager.AddTextParameter("Path", "P", "Path of desired property (Should be ApplicationId).\nExample:'ApplicationId'", GH_ParamAccess.item);
line 37 doesn't need to be there

2020-09-03 16:08 UTC, daviddekoning requested changes
Hi @megankarbowski , it looks like this component is called `ApplicationID` but  behaves more like the `QuerySpeckleObject` ought to.

2020-09-07 21:30 UTC, megankarbowski commented
@daviddekoning @HughGrovesArup all changes are complete except for the new icon!

2020-09-08 08:23 UTC, HughGrovesArup requested changes

2020-09-08 08:23 UTC, HughGrovesArup commented on SpeckleGrasshopper/SpeckleGrasshopper.csproj
> +      <Version>6.28.20199.17141</Version>
Still looks like you are referring to newer package versions?

2020-09-08 08:23 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      : base("Get ApplicationId", "GNV",
I'd change the short name to 'GetId'

2020-09-08 08:23 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +      if (propertyDict.ContainsKey(key))
Because this component is now just getting application id (no user choice) then we can skip the propertyDict check

2020-09-08 16:14 UTC, mkarbows commented
this has been updated again :)

2020-09-08 21:42 UTC, merged