Dev/stam/accounts
arup-group/SpeckleRhino pull request #10
Opened 2020-10-19 12:43 UTC by psarras

This seems like it is going what it is supposed to. However, due to an existing bug, I am a bit uncertain. 
If you orchestrated everything manually instead of relying on the auto refresh, it works. Otherwise, it requires the sender to trigger twice. I think this is a problem only if you have the sender and the receiving component of the same stream on one GH canvas...

Let me know if I am missing something. The sender / receiver component are doing way more than they should so it is hard to have confidence on them, ergo the "Draft PR"

2020-10-19 15:22 UTC, HughGrovesArup commented
@psarras - what's the context of this PR? What should the user be able to do after it is implemented?

2020-10-20 10:22 UTC, psarras commented
@HughGrovesArup The user would be able to optionally add an Account input, using the context menu on the sender component. This would be used to validate the send. As I understand it this is important for Rhino Compute. Hope this makes sense.

2020-10-20 10:44 UTC, HughGrovesArup commented
I cant seem to see that behaviour? What do you see?

![image](https://user-images.githubusercontent.com/40033911/96576114-99068580-12c9-11eb-9fa3-595f209bfe7a.png)

2020-10-20 10:47 UTC, psarras commented
I meant receiver...sorry

2020-10-20 10:58 UTC, HughGrovesArup requested changes
I've not really tested the actual behaviour of these changes as I'm not sure how. Is it to ensure that you are using a specific server when pulling a stream?

2020-10-20 10:58 UTC, HughGrovesArup commented on SpeckleGrasshopper/BaseComponents/GhReceiverCoreClient.cs
> +          Access = GH_ParamAccess.item,
Need to add a description in as well

2020-10-20 10:58 UTC, HughGrovesArup commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
I'm probably out of the loop on this component, but I don't really understand its purpose. Is it really niche? Should it be hidden from regular users if its something only to support TDA?

Also it needs an icon.

2020-10-20 10:58 UTC, HughGrovesArup commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      pManager.AddIntegerParameter("AccountId", "id", "AccountId", GH_ParamAccess.item);
The long descriptions are no more helpful than the parameter names

2020-10-20 11:04 UTC, psarras commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
Good points. @daviddekoning thoughts?

2020-10-20 11:05 UTC, psarras commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
We should probably wait on this PR to do the reorganisation, I guess so we can give it a proper place. As I understand it @HughGrovesArup  it is a bit niche. It would allow you to set the account, without communicating with other servers, provided you have all the credentails.

2020-10-20 11:08 UTC, psarras commented
@HughGrovesArup I am using this script.

[testAccounts.zip](https://github.com/arup-group/SpeckleRhino/files/5408222/testAccounts.zip)

2020-10-20 11:09 UTC, daviddekoning commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
It should be under the 'Advanced' sub-section, but not otherwise hidden. Those are the components that most users should ignore. 

Yes, we'll need an icon. For the GetApplicationID, I just whipped something up in Gimp, but we can also contact a graphic designer within the firm somewhere to give us something. If you guys have a contact, please let me know, otherwise I'll reach out to some folks.

2020-10-20 11:11 UTC, daviddekoning commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
@psarras, @HughGrovesArup - yes, this work is not for this week's release

2020-10-20 11:15 UTC, daviddekoning commented
@HughGrovesArup, this is to allow scripts to run in TDA / rhino.inside, where a single script can be run many times by many people. I'll update things in Jira - there are a few other bits we need to think through as well (e.g. how do we control when a sender creates a new stream vs. updates on old one)

2020-10-20 12:17 UTC, psarras commented on SpeckleGrasshopper/BaseComponents/GhReceiverCoreClient.cs
> +          Access = GH_ParamAccess.item,
Amended this one

2020-10-20 12:18 UTC, psarras commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      pManager.AddIntegerParameter("AccountId", "id", "AccountId", GH_ParamAccess.item);
tried to add a bit more nuance. I think some of them are not needed actually. Through testing it seems only the "Token" + the "Api" are the important ones. I wonder if we just remove the other ones... @daviddekoning any thoughts?

2020-10-20 12:19 UTC, psarras commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
@daviddekoning oops, just saw your comment regarding the icon...argh I've made a quick one as well ...

2020-10-20 12:23 UTC, daviddekoning commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      : base("CreateAccount", "CA",
I ❤️ quick icons

2020-10-20 12:25 UTC, daviddekoning commented on SpeckleGrasshopper/Management/CreateAccount.cs
> +      pManager.AddIntegerParameter("AccountId", "id", "AccountId", GH_ParamAccess.item);
Yea, I think you are right that those are the only important ones. Given that our aim is to write a component that supports the TDA workflow, let's just expose those two. If we need the other info, the component can pull it from the server via the account API.

2020-10-27 19:56 UTC, daviddekoning requested changes
hi @psarras  - this looks good. I've tested it with receivers and I am able to add a receiver to a canvas for one server and then specify an account on another server.

Let's keep going with the other changes we discussed (global setting for manually specifying the account, and adding the ability to specify the account for a sender) and then merge the whole thing

2020-10-28 17:18 UTC, psarras commented
@daviddekoning I added a toggle on the Create Account component that allows to make this a global Account. Also now both sender and receiver have the option to add the Account. Let me know what you think.

2020-10-28 17:20 UTC, daviddekoning commented
By global account, do you mean that you add the account to the Speckle database and it is accessible to all programs on that computer?

2020-10-28 17:21 UTC, daviddekoning commented
We should also be able to specify the stream ID on the sender, but only when it goes into manual mode.

2020-10-28 17:28 UTC, psarras commented
> By global account, do you mean that you add the account to the Speckle database and it is accessible to all programs on that computer?

Nothing so fancy. The sender / receiver look at a static variable if this flag is on. 

> We should also be able to specify the stream ID on the sender, but only when it goes into manual mode.

So the Account iD is the thing that gets specified the stream id, is taken care of from the Client class.
Currently the logic goes: If you have global flag on, then you follow this Account, else you follow the one provided as an input, else you follow the one that is set from the GUI.

2020-11-16 21:36 UTC, daviddekoning commented
I have tested this and it appears to work nicely. There are a couple of rough edges, but I think we should publish a version with this functionality so that the TDA team can start working, then polish it up a bit.

I have pushed a commit with some name changes.

Here are the items I noticed - none of which are showstoppers:

1. If a `Receiver` does not have a StreamId attached, and the global toggle is switched, the `Account` input does not appear. The input appears when you attach a StreamId. 
2. When the mode is switched back to "regular", the account selector popup appears. It would be really nice if the components would remember what the previous account was when they go to Rhino.Compute mode, so that they can continue behaving as they did before if it is switched off. That being said - this is a good behaviour for now.
3. When Rhino.Compute mode is on, if you drop a new Receiver onto the canvas, it still asks you to specify the Account (related to item 1 above).
4. It would be great if the Speckle Menu item `Toggle Rhino.Compute mode` had a checkmark to reflect the current mode.

In summary - let's get this merged into the the main branch and create a release so that the TDA team can start putting it through it's paces. We will then update it based on their feedback, possibly incorporating the above points.

2020-11-16 21:37 UTC, daviddekoning approved these changes

2020-11-19 17:12 UTC, psarras commented
@daviddekoning 

I think 1), should be and easy fix. 
2, 3 are related and they will be a bit much for this PR although definitely doable. Was this the previous behaviour? If I broke it, I would like to bring this back!

4) I think there should be a way. I will have a look.

BTW the stam/dev/sychronous is quite a small change, maybe we can include it here? I think it is important for TDA.

2020-11-19 17:45 UTC, daviddekoning commented
Thanks @psarras. I dot think 2&3 are regressions, just new behaviours that emerged when we made the changes.

Yes, please include the synchronous changes here - then all the Rhino.Compute functionality are included in one place. 

One last thing, can you set up some tests to make sure that the components work reliably with Rhino.compute mode off. I don't mind if the new functionality is a bit flaky, but we should not compromise the old behaviour.

2020-12-09 20:51 UTC, daviddekoning commented
Hi @psarras, the overall UX behaviour is good, however, there seems to be some bugginess in sending/receiving data in Rhino.Compute mode.

1. Receivers sometimes need to be force refreshed after being switched into R.C mode. To reproduce:
    1. Add a receiver to a canvas
    2. Toggle R.C mode to "On"
    3. Connect a streamId and account
    4. Data may preview in the Rhino window, but is not output from the output parameter
    5. Force refresh the component, and all is good
2. Senders aren't always sending all data when the inputs update.

2020-12-10 12:00 UTC, psarras commented
@daviddekoning 

I think the 1) / 2) are existing behaviours that I raised in the past? Generally on the Sender there is a debouncer that is preventing some of the inputs to be send. On the receiver I have noticed that because this works with events, it is a bit precarious if while you are updating you are receiving data as well.

I will double check on 1) If there is any funny business specific to switching th R.C on and get back to you!

2021-01-12 14:52 UTC, merged