Spec 101 get property component
arup-group/SpeckleRhino pull request #3
Opened 2020-09-23 15:06 UTC by megankarbowski

2020-09-23 19:35 UTC, daviddekoning requested changes
Hi Megan,

This is just to record what we discussed:

1. The component should continue processing after an error.
2. The output structure should be the same when there is an error.
3. The error message should
  A: give the name of the key that could not be found (full key, e.g. `Properties.structural.PropertyRef`)
  B: be the same whether the missing key is top level, or further down the chain
4. The component should not look in the `Properties` dictionary unless the key explicitly calls for it.
5. The graft option for the Speckle Object component should be on by default.
6. The Abbreviated name should bs QSO, not GNV (I forgot to mention this earlier).

Here is a sample file showing these behaviours: [Query Speckle Object notes.zip](https://github.com/arup-group/SpeckleRhino/files/5271424/Query.Speckle.Object.notes.zip)

2020-09-29 11:28 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent.cs
> +      pManager.AddGenericParameter("Output", "O", "Output value.", GH_ParamAccess.list);
This should be 'item' rather than 'list?

Only time that would be weird is if the returned property is a list, then might need to switch this to list? What if the property was a tree?

2020-09-29 11:28 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent.cs
> +        AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Could not find a parameter with the key, " + key + ", on the input object");
May want to use string interpolation.

`$"Could not find parameter with key: '{key}'."`

2020-09-29 11:28 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent_OBSOLETE.cs
> +    public QuerySpeckleObjectComponent_OBSOLETE()
For tidiness may want to create a folder for obsolete components.

2020-09-29 11:28 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent_OBSOLETE.cs
> +    public QuerySpeckleObjectComponent_OBSOLETE()
e.g. SpeckleGrasshopper\Obsolete

2020-09-29 11:29 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent.cs
> +      pManager.AddGenericParameter("Output", "O", "Output value.", GH_ParamAccess.list);
I think the list / tree would be relatively rare? Would be interested to see real-world examples, and how the component would behave. I'd suggest making it 'item' for the time being.

I note in the original component they try to be a bit smarter about it, but it does add complexity.

2020-10-12 19:40 UTC, megankarbowski commented
ok - sorry for the delay on this - it should be ready to go.

2020-10-13 01:46 UTC, daviddekoning commented
Thanks, @megankarbowski, this looks great.

One final little thing regarding the Warning messages: if a sub property is not found, the warning only gives the last part of the property name. For instance, if you ask for `Properties.NotAProperty`, the warning says that `NotAProperty` wasn't found. Instead it should say `Properties.NotAProperty` wasn't found.

2020-10-15 00:09 UTC, megankarbowski commented
this should be ready for one last review before being merged to master

2020-10-15 12:41 UTC, daviddekoning commented
Thanks @megankarbowski - the component looks great. There appears, however, to be something wrong with the merge into master.

@psarras, since Megan is off for the rest of the week, could you re-merge from commit 16240c33efc607a2fbc1f5bf0f5d4c93fe1952b6 to master. The key thing to watch for is that the old `QuerySpeckleObjectComponent.cs` has been renamed to `QuerySpeckleObjectComponent_OBSOLETE.cs` and there is a whole new file called `QuerySpeckleObjectComponent.cs`, which confuses git.

2020-10-15 14:02 UTC, closed without merging