SPEC-52
arup-group/SpeckleRhino pull request #4
Opened 2020-09-23 20:29 UTC by megankarbowski

if a SpeckleObject is connected to an input with Ref, get the ApplicationId

2020-09-23 21:32 UTC, daviddekoning requested changes
Apart from my one comment, this looks great! This single change is going to have huge benefits!!

2020-09-23 21:32 UTC, daviddekoning commented on SpeckleGrasshopper/ObjectCreation/SchemaBuilderComponent.cs
> +          if (Params.Input[i].Name.Contains("Ref"))
Can we make this check if the Parma name *ends* in Ref, rather than contains? That will limit side effects

2020-09-29 11:30 UTC, HughGrovesArup approved these changes
Looks good to me

2020-09-29 11:57 UTC, daviddekoning approved these changes

2020-09-29 15:46 UTC, merged

2020-09-30 09:32 UTC, HughGrovesArup commented
@megankarbowski - this is good to go into master, no need to keep everything on megan/dev. The publishing pipelines are only set up to operate on `master`. With this change I can update and release the documentation.