Component reorganization
arup-group/SpeckleRhino pull request #9
Opened 2020-10-17 14:18 UTC by daviddekoning

This is re-organizes the components in the toolbar and hides non-core components.

2020-10-19 08:41 UTC, HughGrovesArup requested changes
Some minor tweaks suggested

2020-10-19 08:41 UTC, HughGrovesArup commented on SpeckleGrasshopper/BaseComponents/GhReceiverCoreClient.cs
> +      : base( "     Data Receiver", "DR",
I know that you have done this to get everything to list correctly, but it just looks really horrible! I think its worth it for the categories, but not for the listing of components within each category.

2020-10-19 08:41 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/CreateLotsOfUserData.cs
> +      : base( "  Create Lots of Custom User Data", "CLUD",
Agree with the commentators - what is 'lots' in this context?

2020-10-19 08:41 UTC, HughGrovesArup commented on SpeckleGrasshopper/UserDataUtils/CreateLotsOfUserData.cs
> +      : base( "  Create Lots of Custom User Data", "CLUD",
Didnt really understand how these components work - just did a bit of investigation. Its two different ways of achieving the same thing really. Always a bit confusing when there are multiple ways to do the same thing. Would be better if the same component could transform modes depending on a right-click menu? I don't think the lots / not lots signifier accurate describes the difference in operation (named input vs. string inputs)

2020-10-19 08:41 UTC, HughGrovesArup commented on SpeckleRhinoPlugin/SpeckleWinR6/Properties/AssemblyInfo.cs
> +// NOTE: these version numbers are to be ovewritten in the CI/CD process
// NOTE: these version numbers are overwritten in the CI/CD process

2020-10-19 08:55 UTC, psarras requested changes
Hey @daviddekoning I think there are some styling changes required. I haven't repeated the same comment on every line, but can do if you think this is useful.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/BaseComponents/GhReceiverCoreClient.cs
> +          "Speckle", "   Server" )
The "   Server" here includes spaces infront. Same as on line 55 there are empty spaces on the component name.
This continues on various components, I will not mark them but I think they should be fixed.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/ExtendedComponents/MeshTexCoords.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
I am not sure how we decide what to hide. To my mind we should hide components, that have been deprecated, or are only working for older versions. This particular one seems like a very specialised tool, I will either put it on a "Utilities" section or remove it as you have it depending on if it works for the current version. I will comment on the others, what I think.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/ExtendedComponents/XmlToSpeckleObject.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
I will either put it on a "Utilities" section or remove it as you have it depending on if it works for the current version.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/Management/AddStreamsToProject.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
I will keep this visible on the new section Server.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/TestComponents/SpeckleConverterDebug.cs
>      public DecodeFromSpeckle()
This should be in a separate file! Maybe good opportunity to do it now?

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/UserDataUtils/ExpandUserDataComponent.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
This should be on the top of the class. I notice some of them are all over the class, properties should be on the top, all grouped together. I might have missed some but consider this comment for all of them. I will try to mark it to as many as I can find.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/UserDataUtils/GetApplicationId.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
further up, sounds good to hide it.

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/UserDataUtils/GetUserDataComponent.cs
> +        public override Grasshopper.Kernel.GH_Exposure Exposure
Further up, and maybe use the same style ( => GH_Exposure.hidden;)

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/UserDataUtils/GetValueAtKey.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
further up

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent.cs
> +      : base("     Query Speckle Object", "QSO",
A gap here as well

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/UserDataUtils/SetUserDataComponent.cs
> +    }
Further up, and maybe use the same style ( => GH_Exposure.hidden;)

2020-10-19 08:55 UTC, psarras commented on SpeckleGrasshopper/ExtendedComponents/MeshTexCoords.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
Further up

2020-10-19 18:37 UTC, daviddekoning commented on SpeckleGrasshopper/BaseComponents/GhReceiverCoreClient.cs
> +      : base( "     Data Receiver", "DR",
problem solved: http://www.unicode-symbol.com/u/200B.html

2020-10-19 18:49 UTC, daviddekoning commented on SpeckleGrasshopper/BaseComponents/GhReceiverCoreClient.cs
> +          "Speckle", "   Server" )
the spacing is a hack to control the ordering of the components. I have switched to spaces to zero-width spaces: U+200B

2020-10-19 18:51 UTC, daviddekoning commented on SpeckleGrasshopper/ExtendedComponents/MeshTexCoords.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
from what I understand, this is a community-contributed component that was never widely used. I have not heard of it being used within Arup. We can add it back to a `Misc` or `Utilities` category if anyone asks for it.

2020-10-19 18:52 UTC, daviddekoning commented on SpeckleGrasshopper/Management/AddStreamsToProject.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
the functionality is replaced by the work you did adding a project parameter to the Sender. This reorg is aiming to simplify the choices a new user needs to make, so it's best to just show one way of doing things.

2020-10-19 18:54 UTC, daviddekoning commented on SpeckleGrasshopper/ExtendedComponents/XmlToSpeckleObject.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
we can always re-expose it if anyone is using it

2020-10-19 18:54 UTC, daviddekoning commented on SpeckleGrasshopper/TestComponents/SpeckleConverterDebug.cs
>      public DecodeFromSpeckle()
yes, it could be, but it's not the focus of this work :)

2020-10-19 18:55 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/GetUserDataComponent.cs
> +        public override Grasshopper.Kernel.GH_Exposure Exposure
ah, I missed one

2020-10-19 18:56 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/QuerySpeckleObjectComponent.cs
> +      : base("     Query Speckle Object", "QSO",
replaced with U+200B

2020-10-19 20:03 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/CreateLotsOfUserData.cs
> +      : base( "  Create Lots of Custom User Data", "CLUD",
that is a good point, but I don't think we have enough information to make the right decision at the moment. For the sake of moving forward, I have renamed them to `Create Properties by Key` and `Create Properties by List`. I have moved `Create Properties by List` to the `Advanced` panel.

2020-10-19 20:07 UTC, daviddekoning commented on SpeckleGrasshopper/UserDataUtils/ExpandUserDataComponent.cs
> +    public override GH_Exposure Exposure => GH_Exposure.hidden;
I have moved some of them up and cleaned up they style.

for the wider questions of style, etc... let's include some clean up in the next bit of plugin upgrade.

2020-10-19 20:18 UTC, daviddekoning commented
@HughGrovesArup, @psarras - I've made updates as per your commnets, thanks!

I am happy with this. @HughGrovesArup, unless you have further release captain-related concerns, let's merge and release!

2020-10-20 09:38 UTC, psarras commented
Hey @daviddekoning, Hugh explained me why you have added those odd symbols. Would you perhaps consider using the GH_Exposure variable to put the components in different subsections? I changed the first 5 components and this is the end result on the right (left is the original from your video)

![image](https://user-images.githubusercontent.com/3820417/96568757-31980800-12c0-11eb-8b10-e18c32833c01.png)

The way to solve this is using the exposure like so:

```cs
// For the first section
public override GH_Exposure Exposure => GH_Exposure.primary;
// For the second section
public override GH_Exposure Exposure => GH_Exposure.secondary;
```

2020-10-20 10:31 UTC, HughGrovesArup commented
@psarras - that looks neater, if it's a quick fix can you please implement. If everything else is ready I wont wait for this change to merge and release though.

2020-10-20 10:46 UTC, psarras commented
@HughGrovesArup The release is end of the day? It is a quick fix, I've done it for the server section. but I can skip it for the ones that it is impossible, like the "Create" subsection.

2020-10-20 10:47 UTC, HughGrovesArup commented
Sure thing

2020-10-20 11:23 UTC, psarras commented
@daviddekoning Shouldn't we consolidate those?

- Create Properties by Key (Currently on Properties)
- Create Properties by List (Currently on Advanced)
- Create Speckle Object (Currently on Create)

We can easily put all of them under Create?

2020-10-20 11:30 UTC, daviddekoning commented
The current layout is deliberate, to give a simple mental flow: connect, create, add properties. I moved the CPL property to advanced so that new users will be able to just get started without having to decide between CPL and CPK.

2020-10-20 12:58 UTC, HughGrovesArup commented
OK with Stam's changes I think this is good to go now

2020-10-20 12:58 UTC, merged